name: ${project.name}
main: net.daboross.bukkitdev.redstoneclockdetector.RCDPlugin
version: ${minecraft.plugin.version}
api-version: 1.14

description: Detect redstone clock and teleport to it.
authors: [HWei, daboross, Phoenix616]
commands:
  rcd:
    aliases: redstoneclockdetector
    description: Redstone clock detector base command.
    usage: /<command> ?
permissions:
  redstoneclockdetector.*:
    description: Gives access to use this plugin.
    default: op
    children:
      redstoneclockdetector: true
      redstoneclockdetector.start: true
      redstoneclockdetector.stop: true
      redstoneclockdetector.list: true
      redstoneclockdetector.tp: true
      redstoneclockdetector.break: true
      redclockdetector.broadcast.send: true
      redclockdetector.broadcast.receive: true
  redstoneclockdetector:
    description: Show status of plugin.
  redstoneclockdetector.start:
    description: Start scan.
  redstoneclockdetector.stop:
    description: Stop scan.
  redstoneclockdetector.list:
    description: List locations of redstone activities.
  redstoneclockdetector.tp:
    description: Teleport a player to a location in list.
  redstoneclockdetector.break:
    description: Break the block at a location in list.
  redclockdetector.broadcast.send:
    description: Start a search which broadcasts to all users with redclockdetector.broadcast.receive permission.
  redclockdetector.broadcast.receive:
    description: Receive informations about searches started with the broadcast option.

 
