name: ${project.name}
main: net.daboross.bukkitdev.redstoneclockdetector.RCDPlugin
version: ${project.version}
api-version: 1.14

description: Detect redstone clock and teleport to it.
author: HWei, daboross
commands:
  rcd:
    aliases: redstoneclockdetector
    description: Redstone clock detector base command.
    usage: /<command> ?
permissions:
  redstoneclockdetector.*:
    description: Gives access to use this plugin.
    default: op
    children:
      redstoneclockdetector: true
      redstoneclockdetector.start: true
      redstoneclockdetector.stop: true
      redstoneclockdetector.list: true
      redstoneclockdetector.tp: true
      redstoneclockdetector.break: true
  redstoneclockdetector:
    description: Show status of plugin.
  redstoneclockdetector.start:
    description: Start scan.
  redstoneclockdetector.stop:
    description: Stop scan.
  redstoneclockdetector.list:
    description: List locations of redstone activities.
  redstoneclockdetector.tp:
    description: Teleport a player to a location in list.
  redstoneclockdetector.break:
    description: Break the block at a location in list.
    

 
